# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'login.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)
import resourece_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1270, 650)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QSize(1270, 650))
        Dialog.setMaximumSize(QSize(1270, 650))
        icon = QIcon()
        icon.addFile(u":/ui/ui/images/icon2.png", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.background = QLabel(Dialog)
        self.background.setObjectName(u"background")
        self.background.setEnabled(True)
        self.background.setGeometry(QRect(0, 0, 1920, 1080))
        self.background.setPixmap(QPixmap(u":/ui/ui/images/main_bg2.jpg"))
        self.background.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self.background.setWordWrap(False)
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 1270, 650))
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(0, 0))
        self.frame.setMaximumSize(QSize(1270, 650))
        self.frame.setStyleSheet(u"background-color: rgba(0, 0, 0, 109);")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.login_frame = QFrame(self.frame)
        self.login_frame.setObjectName(u"login_frame")
        self.login_frame.setGeometry(QRect(360, 60, 550, 481))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(5)
        sizePolicy1.setVerticalStretch(5)
        sizePolicy1.setHeightForWidth(self.login_frame.sizePolicy().hasHeightForWidth())
        self.login_frame.setSizePolicy(sizePolicy1)
        self.login_frame.setMinimumSize(QSize(550, 400))
        self.login_frame.setMaximumSize(QSize(550, 507))
        self.login_frame.setStyleSheet(u"background-color: rgb(13, 16, 23);\n"
"border-radius: 20px")
        self.login_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.login_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.id_input = QLineEdit(self.login_frame)
        self.id_input.setObjectName(u"id_input")
        self.id_input.setGeometry(QRect(88, 130, 380, 25))
        sizePolicy.setHeightForWidth(self.id_input.sizePolicy().hasHeightForWidth())
        self.id_input.setSizePolicy(sizePolicy)
        self.id_input.setStyleSheet(u"font-size:11pt;\n"
"color: rgb(255, 255, 255);")
        self.pw_input = QLineEdit(self.login_frame)
        self.pw_input.setObjectName(u"pw_input")
        self.pw_input.setGeometry(QRect(88, 206, 380, 25))
        sizePolicy.setHeightForWidth(self.pw_input.sizePolicy().hasHeightForWidth())
        self.pw_input.setSizePolicy(sizePolicy)
        self.pw_input.setStyleSheet(u"font-size:14pt;\n"
"color: rgb(255, 255, 255);")
        self.pw_input.setEchoMode(QLineEdit.EchoMode.Password)
        self.pw_input.setCursorPosition(0)
        self.login_bn = QPushButton(self.login_frame)
        self.login_bn.setObjectName(u"login_bn")
        self.login_bn.setGeometry(QRect(50, 408, 461, 45))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(1)
        sizePolicy2.setHeightForWidth(self.login_bn.sizePolicy().hasHeightForWidth())
        self.login_bn.setSizePolicy(sizePolicy2)
        font = QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.login_bn.setFont(font)
        self.login_bn.setStyleSheet(u"background-color: rgb(30, 195, 55);\n"
"border-radius: 10px;\n"
"color: rgb(252, 252, 252);")
        self.id_line = QFrame(self.login_frame)
        self.id_line.setObjectName(u"id_line")
        self.id_line.setGeometry(QRect(88, 160, 391, 1))
        sizePolicy.setHeightForWidth(self.id_line.sizePolicy().hasHeightForWidth())
        self.id_line.setSizePolicy(sizePolicy)
        self.id_line.setMaximumSize(QSize(16777215, 1))
        font1 = QFont()
        font1.setPointSize(5)
        font1.setStrikeOut(False)
        self.id_line.setFont(font1)
        self.id_line.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.id_line.setAutoFillBackground(False)
        self.id_line.setStyleSheet(u"background-color: rgb(36, 39, 44)")
        self.id_line.setFrameShape(QFrame.Shape.HLine)
        self.id_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.pw_line = QFrame(self.login_frame)
        self.pw_line.setObjectName(u"pw_line")
        self.pw_line.setGeometry(QRect(86, 235, 391, 1))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.pw_line.sizePolicy().hasHeightForWidth())
        self.pw_line.setSizePolicy(sizePolicy3)
        self.pw_line.setFont(font1)
        self.pw_line.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.pw_line.setAutoFillBackground(False)
        self.pw_line.setStyleSheet(u"background-color: rgb(36, 39, 44)")
        self.pw_line.setFrameShape(QFrame.Shape.HLine)
        self.pw_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.logo = QLabel(self.login_frame)
        self.logo.setObjectName(u"logo")
        self.logo.setGeometry(QRect(160, 24, 251, 41))
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setPixmap(QPixmap(u":/ui/ui/images/logo.png"))
        self.logo.setScaledContents(True)
        self.label = QLabel(self.login_frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(88, 98, 91, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.label.setFont(font2)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2 = QLabel(self.login_frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(88, 176, 91, 31))
        self.label_2.setFont(font2)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ai_server_ip_line = QFrame(self.login_frame)
        self.ai_server_ip_line.setObjectName(u"ai_server_ip_line")
        self.ai_server_ip_line.setGeometry(QRect(88, 312, 391, 1))
        sizePolicy3.setHeightForWidth(self.ai_server_ip_line.sizePolicy().hasHeightForWidth())
        self.ai_server_ip_line.setSizePolicy(sizePolicy3)
        self.ai_server_ip_line.setMaximumSize(QSize(16777215, 1))
        self.ai_server_ip_line.setFont(font1)
        self.ai_server_ip_line.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.ai_server_ip_line.setAutoFillBackground(False)
        self.ai_server_ip_line.setStyleSheet(u"background-color: rgb(36, 39, 44)")
        self.ai_server_ip_line.setFrameShape(QFrame.Shape.HLine)
        self.ai_server_ip_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_3 = QLabel(self.login_frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(88, 250, 121, 31))
        self.label_3.setFont(font2)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ai_server_ip_input = QLineEdit(self.login_frame)
        self.ai_server_ip_input.setObjectName(u"ai_server_ip_input")
        self.ai_server_ip_input.setGeometry(QRect(88, 282, 380, 25))
        sizePolicy.setHeightForWidth(self.ai_server_ip_input.sizePolicy().hasHeightForWidth())
        self.ai_server_ip_input.setSizePolicy(sizePolicy)
        self.ai_server_ip_input.setStyleSheet(u"font-size:11pt;\n"
"color: rgb(255, 255, 255);")
        self.label_4 = QLabel(self.login_frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(88, 330, 131, 31))
        self.label_4.setFont(font2)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ai_server_port_line = QFrame(self.login_frame)
        self.ai_server_port_line.setObjectName(u"ai_server_port_line")
        self.ai_server_port_line.setGeometry(QRect(88, 392, 391, 1))
        sizePolicy.setHeightForWidth(self.ai_server_port_line.sizePolicy().hasHeightForWidth())
        self.ai_server_port_line.setSizePolicy(sizePolicy)
        self.ai_server_port_line.setMaximumSize(QSize(16777215, 1))
        self.ai_server_port_line.setFont(font1)
        self.ai_server_port_line.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.ai_server_port_line.setAutoFillBackground(False)
        self.ai_server_port_line.setStyleSheet(u"background-color: rgb(36, 39, 44)")
        self.ai_server_port_line.setFrameShape(QFrame.Shape.HLine)
        self.ai_server_port_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.ai_server_port_input = QLineEdit(self.login_frame)
        self.ai_server_port_input.setObjectName(u"ai_server_port_input")
        self.ai_server_port_input.setGeometry(QRect(88, 362, 380, 25))
        sizePolicy.setHeightForWidth(self.ai_server_port_input.sizePolicy().hasHeightForWidth())
        self.ai_server_port_input.setSizePolicy(sizePolicy)
        self.ai_server_port_input.setStyleSheet(u"font-size:11pt;\n"
"color: rgb(255, 255, 255);")
        QWidget.setTabOrder(self.id_input, self.pw_input)
        QWidget.setTabOrder(self.pw_input, self.ai_server_ip_input)
        QWidget.setTabOrder(self.ai_server_ip_input, self.ai_server_port_input)
        QWidget.setTabOrder(self.ai_server_port_input, self.login_bn)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"login", None))
        self.background.setText("")
        self.id_input.setText("")
        self.pw_input.setText("")
        self.login_bn.setText(QCoreApplication.translate("Dialog", u"\ub85c\uadf8\uc778", None))
        self.logo.setText("")
        self.label.setText(QCoreApplication.translate("Dialog", u"\uc544\uc774\ub514", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"\ube44\ubc00\ubc88\ud638", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"\uc9c0\ub2a5\ud615 \uc11c\ubc84 IP", None))
        self.ai_server_ip_input.setText("")
        self.label_4.setText(QCoreApplication.translate("Dialog", u"\uc9c0\ub2a5\ud615\uc11c\ubc84 PORT", None))
        self.ai_server_port_input.setText("")
    # retranslateUi

